(ns dynne.sound.impl
  "Internal implementation details of the dynn.sound namespace. Use
  functions there in preference to working with these directly.")

(defprotocol Sound
  "Defines a notional sound."
  (duration [sound] "Returns the duration of the sound in seconds.")
  (amplitudes [sound t] "A function of one argument (a time in seconds) that returns a vector
  of floating point numbers representing the amplitidue of each
  channel at that point in time."))

(defprotocol ChannelCount
  "Support for efficiently returning the number of channels in a sound."
  (num-channels [sound] "Returns the number of channels in a sound."))

;; A simple in-memory sound generated by the `sampler` function
(defrecord BasicSound [duration sampler]
  Sound
  (duration [this] (:duration this))
  (amplitudes [this t] ((:sampler this) t)))

